/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /** Creates new form MenúPrincipal */
    public MenuPrincipal() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new Styles.JpanelRound();
        jpanelRound2 = new Styles.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnTIncidencias = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnREmpleados = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnRAreas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnAPersonal = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnRSolución = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        btnIncidencias = new RSMaterialComponent.RSButtonMaterialIconDos();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRound2.setBackground(new java.awt.Color(153, 0, 51));
        jpanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú Principal");
        jpanelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnSalir.setBackground(new java.awt.Color(153, 0, 51));
        btnSalir.setText("Salir");
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnSalir.setInheritsPopupMenu(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, -1));

        btnTIncidencias.setBackground(new java.awt.Color(153, 0, 51));
        btnTIncidencias.setText("Tipo de Incidencias");
        btnTIncidencias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DETAILS);
        btnTIncidencias.setInheritsPopupMenu(true);
        btnTIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTIncidenciasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnTIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        btnREmpleados.setBackground(new java.awt.Color(153, 0, 51));
        btnREmpleados.setText("Registro de Empleados");
        btnREmpleados.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP_ADD);
        btnREmpleados.setInheritsPopupMenu(true);
        btnREmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREmpleadosActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnREmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        btnRAreas.setBackground(new java.awt.Color(153, 0, 51));
        btnRAreas.setText("Registro de Áreas");
        btnRAreas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INPUT);
        btnRAreas.setInheritsPopupMenu(true);
        btnRAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAreasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnRAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, -1));

        btnAPersonal.setBackground(new java.awt.Color(153, 0, 51));
        btnAPersonal.setText("Asignación de Personal");
        btnAPersonal.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP);
        btnAPersonal.setInheritsPopupMenu(true);
        btnAPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPersonalActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnAPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, -1));

        btnRSolución.setBackground(new java.awt.Color(153, 0, 51));
        btnRSolución.setText("Registro de Solución");
        btnRSolución.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnRSolución.setInheritsPopupMenu(true);
        btnRSolución.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSoluciónActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnRSolución, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 210, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jpanelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 220, 10));

        btnIncidencias.setBackground(new java.awt.Color(153, 0, 51));
        btnIncidencias.setText("Incidencias");
        btnIncidencias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTE);
        btnIncidencias.setInheritsPopupMenu(true);
        btnIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidenciasActionPerformed(evt);
            }
        });
        jpanelRound2.add(btnIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, -1));

        jpanelRound1.add(jpanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setMinimumSize(new java.awt.Dimension(740, 540));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jpanelRound1.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 750, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTIncidenciasActionPerformed

    private void btnREmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnREmpleadosActionPerformed

    private void btnRAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRAreasActionPerformed

    private void btnAPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAPersonalActionPerformed

    private void btnRSoluciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSoluciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRSoluciónActionPerformed

    private void btnIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncidenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonMaterialIconDos btnAPersonal;
    public RSMaterialComponent.RSButtonMaterialIconDos btnIncidencias;
    public RSMaterialComponent.RSButtonMaterialIconDos btnRAreas;
    public RSMaterialComponent.RSButtonMaterialIconDos btnREmpleados;
    public RSMaterialComponent.RSButtonMaterialIconDos btnRSolución;
    public RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    public RSMaterialComponent.RSButtonMaterialIconDos btnTIncidencias;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private Styles.JpanelRound jpanelRound1;
    private Styles.JpanelRound jpanelRound2;
    // End of variables declaration//GEN-END:variables

}
